/* Fictitious adults; existing illustration photos, no real member data. */
const rows = [
 ['alex','Alex',32,'Paris',['Leather','Denim'],'Dom','suivi','Prendre le temps','Un café sans regarder l’heure. Et l’envie de se revoir.','Les échanges francs, le cuir et les dimanches à deux.'],
 ['tom','Tom',28,'Lyon',['Sportswear'],'Switch','verre','Se rencontrer bientôt','Un verre après le sport. On voit où le feeling nous mène.','Baskets aux pieds, esprit ouvert. Le premier rendez-vous peut rester tout simple.'],
 ['max','Max',35,'Bordeaux',['Rubber','Bondage'],'Switch','explorer','Prendre le temps','Partager la passion du gear, puis inventer nos propres codes.','Collectionneur de matières et amateur de conversations qui durent.'],
 ['leo','Léo',30,'Paris',['Sportswear','Denim'],'Sans étiquette','verre','Se rencontrer bientôt','Une terrasse, deux sourires, aucune idée préconçue.','J’aime la spontanéité, le nylon et les gens qui écoutent.'],
 ['noe','Noé',26,'Lille',['Denim','Leather'],'Sub','suivi','Prendre le temps','Le même rire. Et peut-être le même prochain week-end.','Plutôt introverti au début. Les choses simples font les meilleures histoires.'],
 ['sacha','Sacha',38,'Paris',['Bondage','Rubber'],'Dom','explorer','Prendre le temps','Apprendre les envies de l’autre avant tout le reste.','Curieux, patient, attaché à la confiance et à la discussion.'],
 ['eli','Eli',29,'Nantes',['Puppy','Sportswear'],'Switch','verre','Se rencontrer bientôt','Un premier verre et beaucoup d’autodérision.','J’aime jouer, sortir de mes habitudes et rencontrer des personnalités singulières.'],
 ['adam','Adam',42,'Marseille',['Leather','Denim'],'Dom','suivi','Prendre le temps','Quelqu’un avec qui les petits rituels deviennent précieux.','La mer, le cuir patiné, un bon dîner et le plaisir de prendre le temps.'],
 ['yan','Yan',33,'Lyon',['Rubber','Sportswear'],'Sub','explorer','Se rencontrer bientôt','Tu me fais découvrir ton univers ? Je te raconte le mien.','Une nouvelle rencontre commence pour moi par une vraie conversation.'],
 ['milo','Milo',24,'Bordeaux',['Denim'],'Sans étiquette','verre','Prendre le temps','Pas besoin de tout savoir pour avoir envie de découvrir.','Nouveau dans ces univers. J’apprécie qu’on puisse poser des questions simplement.'],
 ['raph','Raph',46,'Paris',['Leather','Bondage'],'Switch','suivi','Se rencontrer bientôt','Garder la curiosité du premier rendez-vous, même après dix.','Je cherche une complicité qui laisse de la place à chacun.'],
 ['jules','Jules',31,'Nantes',['Puppy','Rubber'],'Sans étiquette','explorer','Prendre le temps','Une envie commune, et toute une personne à découvrir.','J’aime les échanges légers qui deviennent des conversations profondes.']
];
window.KINQ_DEMO_PROFILES=rows.map(([id,name,age,city,kinks,role,intent,pace,quote,bio],i)=>({id,name,age,city,kinks,role,intent,pace,quote,bio,photo:({"alex": "https://static.wixstatic.com/media/739d69_8f8ce9ef74c34d25803f679a3f8127e4~mv2.jpg/v1/fill/w_480%2Ch_720%2Cal_c%2Cq_80%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/739d69_8f8ce9ef74c34d25803f679a3f8127e4~mv2.jpg", "tom": "https://mr-riegillio.com/cdn/shop/articles/sylven-meets-rj-585763.jpg?v=1607874225&width=1200", "max": "https://www.invinciblerubber.com/image/cache/catalog/SU056_h-840x840.jpg", "leo": "https://www.scallychav.co.uk/cdn/shop/files/FDCA6A7D-D889-4DFA-AD34-30F6174243C3.jpg?v=1778270620&width=1445"})[id]||null,code:({alex:"KQ-7M4X9P",tom:"KQ-8N2R6T",max:"KQ-3W9F5A",leo:"KQ-6B2D8H"})[id]||`KQ-DEMO${String(i+1).padStart(2,"0")}`}));
