let me, tab='photos', articles=[];
const tabMeta={photos:['MODÉRATION','Photos à valider'],members:['COMPTES & SÉCURITÉ','Comptes membres'],articles:['JOURNAL','NO TABOO'],comments:['MODÉRATION','Commentaires'],staff:['ACCÈS','Équipe & accès'],analytics:['PARAMÈTRES','Mesure d’audience']};
const $=s=>document.querySelector(s), content=$('#content');
const legacyCommentSlugs=new Set(['premiers-pas','parler-de-ses-limites','les-mots-pour-se-comprendre','profil-et-vie-privee','premiere-rencontre','aftercare']);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(me?{'X-CSRF-Token':me.csrf}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error((await response.text()).slice(0,180));return response.status===204?null:response.json()}
function notice(message){$('#notice').textContent=message;setTimeout(()=>{$('#notice').textContent=''},5000)}
function heading(title,subtitle,extra=''){return `<div class="section-head"><div><h2>${title}</h2><p>${subtitle}</p></div>${extra}</div>`}
async function load(){try{me=await api('/admin/me');$('#login').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=me.email;$('#logout').hidden=false;render()}catch{$('#login').hidden=false;$('#workspace').hidden=true}}
const authError = new URLSearchParams(location.search).get('auth_error');
if(authError) $('#owner-login-status').textContent = ({state:'La session a expiré. Réessaie avec Google.',google:'Connexion Google interrompue. Réessaie.',workspace:'Utilise ton compte Google Workspace @theethercompany.com.',account:'Ce compte Google est déjà lié à une autre identité.'})[authError] || '';
async function render(){const [section,title]=tabMeta[tab];$('#current-section').textContent=section;$('#current-title').textContent=title;try{if(tab==='photos')return photos();if(tab==='members')return members();if(tab==='articles')return articleList();if(tab==='comments')return comments();if(tab==='staff')return staffList();if(tab==='analytics')return analyticsSettings()}catch(e){notice(e.message)}}
async function analyticsSettings(){const setting=await api('/admin/settings/analytics');content.innerHTML=heading('Pixel KINQ','Le même identifiant est utilisé sur le site principal et dans l’espace membre. La mesure démarre uniquement après accord.')+`<form id="analytics-form" class="editor"><label>Identifiant du site<input name="site_id" type="text" spellcheck="false" autocomplete="off" pattern="[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}" value="${esc(setting.site_id)}" ${me.role==='admin'?'':'disabled'}></label><p>Videz le champ pour désactiver le pixel. Le changement s’applique aux prochaines pages chargées.</p>${me.role==='admin'?'<button class="action" type="submit">Enregistrer le pixel</button>':''}</form>`;$('#analytics-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/settings/analytics','PUT',{site_id:new FormData(e.target).get('site_id')});notice('Pixel enregistré')}catch(err){notice(err.message)}})}
async function photos(){const rows=await api('/admin/photos');$('#photo-count').textContent=rows.length;content.innerHTML=heading('Photos à voir','Chaque image reste invisible tant que l’équipe ne l’a pas validée.')+(rows.length?`<div class="cards">${rows.map(p=>`<article class="card"><img class="photo" src="/api/admin/photos/${esc(p.id)}/preview" alt="Photo proposée à la modération"><div class="card-meta"><strong>Compte #${p.member_id}</strong><span class="badge">En attente</span></div><div class="controls"><button data-photo="${p.id}" data-decision="approved">Valider</button><button class="danger" data-photo="${p.id}" data-decision="rejected">Refuser</button></div></article>`).join('')}</div>`:'<div class="empty">Aucune photo à modérer pour le moment.</div>')}
async function members(){const rows=await api('/admin/members');content.innerHTML=heading('Comptes inscrits','Retrouvez les membres et gérez leur accès.')+(rows.length?`<div class="member-toolbar"><label class="member-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="member-search" type="search" placeholder="Nom ou adresse e-mail…" aria-label="Rechercher un membre"></label><span id="member-result-count">${rows.length} compte${rows.length>1?'s':''}</span></div><div class="member-list"><div class="member-list-head"><span>MEMBRE</span><span>GESTION</span></div>${rows.map(m=>`<div class="row member-row"><div><strong>${esc(m.name||m.email)}</strong><small>#${m.id} · ${esc(m.email)} · ${esc(m.status)}${m.ban_until?' · jusqu’au '+esc(new Date(m.ban_until).toLocaleDateString('fr-FR')):''}</small></div><details class="member-actions"><summary>Gérer le compte</summary><div class="controls"><button data-member="${m.id}" data-member-action="edit">Modifier</button><button data-member="${m.id}" data-member-action="suspended">Suspendre</button><button data-member="${m.id}" data-member-action="banned_temporary">Bannir temporairement</button><button data-member="${m.id}" data-member-action="banned_permanent">Bannir définitivement</button><button data-member="${m.id}" data-member-action="active">Réactiver</button>${me.role==='admin'?`<button class="danger" data-member="${m.id}" data-member-action="delete">Supprimer</button>`:''}</div></details></div>`).join('')}</div>`:'<div class="empty">Aucun compte réel connecté pour le moment.</div>')}
async function articleList(){articles=await api('/admin/articles');content.innerHTML=heading('NO TABOO','Rédiger, modifier et publier les articles du journal.','<button class="action" id="new-article">Nouvel article</button>')+(articles.length?articles.map(a=>`<div class="row"><div><strong>${esc(a.title)}</strong><small>/${esc(a.slug)} · ${esc(a.status)}</small></div><div class="controls"><button data-article="${a.id}" data-article-action="edit">Modifier</button><button class="danger" data-article="${a.id}" data-article-action="delete">Supprimer</button></div></div>`).join(''):'<div class="empty">Aucun nouvel article pour le moment.</div>')}
function articleEditor(a){content.innerHTML=heading(a?'Modifier l’article':'Nouvel article','Texte brut pour l’instant ; la publication rend l’article disponible par l’API.')+`<form id="article-form" class="editor"><label>Titre<input name="title" maxlength="255" required value="${esc(a?.title||'')}"></label><label>Slug<input name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="180" required value="${esc(a?.slug||'')}"></label><label>Résumé<textarea name="summary">${esc(a?.summary||'')}</textarea></label><label>Article<textarea name="body" required>${esc(a?.body||'')}</textarea></label><label>État<select name="status"><option value="draft" ${a?.status==='draft'?'selected':''}>Brouillon</option><option value="published" ${a?.status==='published'?'selected':''}>Publié</option></select></label><button class="action">Enregistrer</button></form>`;$('#article-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('/admin/articles'+(a?'/'+a.id:''),a?'PUT':'POST',data);notice('Article enregistré');articleList()}catch(err){notice(err.message)}})}
async function comments(){const rows=await api('/admin/comments'),pending=rows.filter(c=>c.status==='pending').length;content.innerHTML=heading('Commentaires',`${pending} commentaire${pending===1?'':'s'} en attente · chaque commentaire est relu avant publication.`)+(rows.length?rows.map(c=>`<article class="row comment-row"><div><strong>${esc(c.author_name)} · <a href="${legacyCommentSlugs.has(c.article_slug)?'/':'/journal/'}${esc(c.article_slug)}" target="_blank" rel="noopener">/${esc(c.article_slug)}</a></strong><p>${esc(c.body)}</p><small>${new Date(c.created_at).toLocaleDateString('fr-FR')} · ${c.status==='pending'?'En attente':c.status==='approved'?'Publié':'Refusé'}</small>${c.replies.map(r=>`<div class="comment-team-reply"><strong>Kinq Team</strong><p>${esc(r.body)}</p></div>`).join('')}${c.status==='approved'?`<form class="comment-reply-form" data-comment-reply="${c.id}"><label>Répondre en tant que Kinq Team<textarea name="body" maxlength="2000" required></textarea></label><button class="action" type="submit">Publier la réponse</button></form>`:''}</div><div class="controls">${c.status!=='approved'?`<button data-comment="${c.id}" data-decision="approved">Valider</button>`:''}${c.status!=='rejected'?`<button class="danger" data-comment="${c.id}" data-decision="rejected">${c.status==='approved'?'Masquer':'Refuser'}</button>`:''}</div></article>`).join(''):'<div class="empty">Aucun commentaire pour le moment.</div>')}
async function staffList(){const rows=await api('/admin/staff');content.innerHTML=heading('Équipe Workspace','Chaque collègue crée son accès lors de sa première connexion. Seul le propriétaire KINQ change les rôles.')+rows.map(s=>`<div class="row"><div><strong>${esc(s.name||s.email)}</strong><small>${esc(s.email)} · ${esc(s.role)}</small></div>${me.role==='admin'&&s.role!=='admin'?`<div class="controls"><select data-staff="${s.id}"><option value="user" ${s.role==='user'?'selected':''}>Utilisateur</option><option value="moderator" ${s.role==='moderator'?'selected':''}>Modérateur</option></select></div>`:''}</div>`).join('')}
$('#tabs').addEventListener('click',e=>{const button=e.target.closest('[data-tab]');if(!button)return;tab=button.dataset.tab;document.querySelectorAll('#tabs button').forEach(b=>{b.classList.toggle('active',b===button);if(b===button)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});render()});
content.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='new-article')return articleEditor();if(b.dataset.photo){await api('/admin/photos/'+b.dataset.photo,'PATCH',{status:b.dataset.decision});notice('Photo traitée');return photos()}if(b.dataset.member){const id=b.dataset.member,action=b.dataset.memberAction;if(action==='edit'){const name=prompt('Nouveau nom du compte');if(name!==null)await api('/admin/members/'+id,'PATCH',{name})}else if(action==='delete'){if(!confirm('Supprimer ce compte et ses photos ?'))return;await api('/admin/members/'+id,'DELETE')}else{let until=null;if(action==='banned_temporary'){const value=prompt('Date de fin (AAAA-MM-JJ)');if(!value)return;until=new Date(value+'T23:59:59Z').toISOString()}await api('/admin/members/'+id+'/status','PATCH',{status:action,until})}notice('Compte mis à jour');return members()}if(b.dataset.article){const a=articles.find(a=>a.id===Number(b.dataset.article));if(b.dataset.articleAction==='edit')return articleEditor(a);if(!confirm('Supprimer cet article ?'))return;await api('/admin/articles/'+a.id,'DELETE');notice('Article supprimé');return articleList()}if(b.dataset.comment){await api('/admin/comments/'+b.dataset.comment,'PATCH',{status:b.dataset.decision});notice('Commentaire traité');return comments()}}catch(err){notice(err.message)}});
content.addEventListener('change',async e=>{if(!e.target.matches('[data-staff]'))return;try{await api('/admin/staff/'+e.target.dataset.staff+'/role','PATCH',{role:e.target.value});notice('Rôle mis à jour')}catch(err){notice(err.message);staffList()}});
content.addEventListener('submit',async e=>{const form=e.target.closest('[data-comment-reply]');if(!form)return;e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await api('/admin/comments/'+form.dataset.commentReply+'/reply','POST',{body:new FormData(form).get('body')});notice('Réponse Kinq Team publiée');comments()}catch(err){button.disabled=false;notice(err.message)}});
content.addEventListener('input',e=>{if(!e.target.matches('#member-search'))return;const query=e.target.value.trim().toLocaleLowerCase('fr');let count=0;content.querySelectorAll('.member-row').forEach(row=>{const match=row.querySelector('div:first-child').textContent.toLocaleLowerCase('fr').includes(query);row.hidden=!match;if(match)count++});$('#member-result-count').textContent=`${count} compte${count===1?'':'s'}`});
$('#logout').addEventListener('click',async()=>{await api('/admin/auth/logout','POST');location.reload()});
load();
