let me, tab='photos', articles=[];
const $=s=>document.querySelector(s), content=$('#content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(me?{'X-CSRF-Token':me.csrf}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error((await response.text()).slice(0,180));return response.status===204?null:response.json()}
function notice(message){$('#notice').textContent=message;setTimeout(()=>{$('#notice').textContent=''},5000)}
function heading(title,subtitle,extra=''){return `<div class="section-head"><div><h2>${title}</h2><p>${subtitle}</p></div>${extra}</div>`}
async function load(){try{me=await api('/admin/me');$('#login').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=me.email;$('#logout').hidden=false;render()}catch{$('#login').hidden=false;$('#workspace').hidden=true}}
const authError = new URLSearchParams(location.search).get('auth_error');
if(authError) $('#owner-login-status').textContent = ({state:'La session a expiré. Réessaie avec Google.',google:'Connexion Google interrompue. Réessaie.',workspace:'Utilise ton compte Google Workspace @theethercompany.com.',account:'Ce compte Google est déjà lié à une autre identité.'})[authError] || '';
async function render(){try{if(tab==='photos')return photos();if(tab==='members')return members();if(tab==='articles')return articleList();if(tab==='comments')return comments();if(tab==='staff')return staffList()}catch(e){notice(e.message)}}
async function photos(){const rows=await api('/admin/photos');$('#photo-count').textContent=rows.length;content.innerHTML=heading('Photos à voir','Chaque image reste invisible tant que l’équipe ne l’a pas validée.')+(rows.length?`<div class="cards">${rows.map(p=>`<article class="card"><img class="photo" src="/api/admin/photos/${esc(p.id)}/preview" alt="Photo proposée à la modération"><div class="card-meta"><strong>Compte #${p.member_id}</strong><span class="badge">En attente</span></div><div class="controls"><button data-photo="${p.id}" data-decision="approved">Valider</button><button class="danger" data-photo="${p.id}" data-decision="rejected">Refuser</button></div></article>`).join('')}</div>`:'<div class="empty">Aucune photo à modérer pour le moment.</div>')}
async function members(){const rows=await api('/admin/members');content.innerHTML=heading('Comptes inscrits','Suspendre, bannir ou supprimer un compte.')+(rows.length?rows.map(m=>`<div class="row"><div><strong>${esc(m.name||m.email)}</strong><small>#${m.id} · ${esc(m.email)} · ${esc(m.status)}${m.ban_until?' · jusqu’au '+esc(new Date(m.ban_until).toLocaleDateString('fr-FR')):''}</small></div><div class="controls"><button data-member="${m.id}" data-member-action="edit">Modifier</button><button data-member="${m.id}" data-member-action="suspended">Suspendre</button><button data-member="${m.id}" data-member-action="banned_temporary">Bannir temporairement</button><button data-member="${m.id}" data-member-action="banned_permanent">Bannir définitivement</button><button data-member="${m.id}" data-member-action="active">Réactiver</button>${me.role==='admin'?`<button class="danger" data-member="${m.id}" data-member-action="delete">Supprimer</button>`:''}</div></div>`).join(''):'<div class="empty">Aucun compte réel connecté pour le moment.</div>')}
async function articleList(){articles=await api('/admin/articles');content.innerHTML=heading('NO TABOO','Rédiger, modifier et publier les articles du journal.','<button class="action" id="new-article">Nouvel article</button>')+(articles.length?articles.map(a=>`<div class="row"><div><strong>${esc(a.title)}</strong><small>/${esc(a.slug)} · ${esc(a.status)}</small></div><div class="controls"><button data-article="${a.id}" data-article-action="edit">Modifier</button><button class="danger" data-article="${a.id}" data-article-action="delete">Supprimer</button></div></div>`).join(''):'<div class="empty">Aucun nouvel article pour le moment.</div>')}
function articleEditor(a){content.innerHTML=heading(a?'Modifier l’article':'Nouvel article','Texte brut pour l’instant ; la publication rend l’article disponible par l’API.')+`<form id="article-form" class="editor"><label>Titre<input name="title" maxlength="255" required value="${esc(a?.title||'')}"></label><label>Slug<input name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="180" required value="${esc(a?.slug||'')}"></label><label>Résumé<textarea name="summary">${esc(a?.summary||'')}</textarea></label><label>Article<textarea name="body" required>${esc(a?.body||'')}</textarea></label><label>État<select name="status"><option value="draft" ${a?.status==='draft'?'selected':''}>Brouillon</option><option value="published" ${a?.status==='published'?'selected':''}>Publié</option></select></label><button class="action">Enregistrer</button></form>`;$('#article-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('/admin/articles'+(a?'/'+a.id:''),a?'PUT':'POST',data);notice('Article enregistré');articleList()}catch(err){notice(err.message)}})}
async function comments(){const rows=await api('/admin/comments');content.innerHTML=heading('Commentaires','Modération prête pour l’activation future des commentaires.')+(rows.length?rows.map(c=>`<div class="row"><div><strong>Article #${c.article_id} · Membre #${c.member_id}</strong><p>${esc(c.body)}</p><small>${esc(c.status)}</small></div><div class="controls"><button data-comment="${c.id}" data-decision="approved">Valider</button><button data-comment="${c.id}" data-decision="rejected">Refuser</button></div></div>`).join(''):'<div class="empty">Les commentaires ne sont pas encore ouverts aux membres.</div>')}
async function staffList(){const rows=await api('/admin/staff');content.innerHTML=heading('Équipe Workspace','Chaque collègue crée son accès lors de sa première connexion. Seul le propriétaire KINQ change les rôles.')+rows.map(s=>`<div class="row"><div><strong>${esc(s.name||s.email)}</strong><small>${esc(s.email)} · ${esc(s.role)}</small></div>${me.role==='admin'&&s.role!=='admin'?`<div class="controls"><select data-staff="${s.id}"><option value="user" ${s.role==='user'?'selected':''}>Utilisateur</option><option value="moderator" ${s.role==='moderator'?'selected':''}>Modérateur</option></select></div>`:''}</div>`).join('')}
$('#tabs').addEventListener('click',e=>{const button=e.target.closest('[data-tab]');if(!button)return;tab=button.dataset.tab;document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b===button));render()});
content.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='new-article')return articleEditor();if(b.dataset.photo){await api('/admin/photos/'+b.dataset.photo,'PATCH',{status:b.dataset.decision});notice('Photo traitée');return photos()}if(b.dataset.member){const id=b.dataset.member,action=b.dataset.memberAction;if(action==='edit'){const name=prompt('Nouveau nom du compte');if(name!==null)await api('/admin/members/'+id,'PATCH',{name})}else if(action==='delete'){if(!confirm('Supprimer ce compte et ses photos ?'))return;await api('/admin/members/'+id,'DELETE')}else{let until=null;if(action==='banned_temporary'){const value=prompt('Date de fin (AAAA-MM-JJ)');if(!value)return;until=new Date(value+'T23:59:59Z').toISOString()}await api('/admin/members/'+id+'/status','PATCH',{status:action,until})}notice('Compte mis à jour');return members()}if(b.dataset.article){const a=articles.find(a=>a.id===Number(b.dataset.article));if(b.dataset.articleAction==='edit')return articleEditor(a);if(!confirm('Supprimer cet article ?'))return;await api('/admin/articles/'+a.id,'DELETE');notice('Article supprimé');return articleList()}if(b.dataset.comment){await api('/admin/comments/'+b.dataset.comment,'PATCH',{status:b.dataset.decision});notice('Commentaire traité');return comments()}}catch(err){notice(err.message)}});
content.addEventListener('change',async e=>{if(!e.target.matches('[data-staff]'))return;try{await api('/admin/staff/'+e.target.dataset.staff+'/role','PATCH',{role:e.target.value});notice('Rôle mis à jour')}catch(err){notice(err.message);staffList()}});
$('#logout').addEventListener('click',async()=>{await api('/admin/auth/logout','POST');location.reload()});
load();
