from pathlib import Path
import re,json
r=Path(__file__).resolve().parent.parent
s=(r/'index.html').read_text();photos=json.loads((r/'assets/photos.json').read_text())
def icon(n):return f'<svg aria-hidden="true"><use href="#{n}"/></svg>'
def intro(tag,title,desc):return f'<section class="page-intro wrap"><p class="eyebrow">{tag}</p><h1>{title}</h1><p>{desc}</p></section>'
def save(slug,title,body):
 page=re.sub(r'<main>.*?</main>',f'<main id="page-main">{body}</main>',s,flags=re.S)
 page=page.replace('<body>',f'<body data-page="{slug}">').replace('<title>Kinq — Tes kinks. Tes codes. Tes rencontres.</title>',f'<title>{title} — Kinq</title>')
 (r/f'{slug}.html').write_text(page)
filters='<div class="filter-bar" role="group" aria-label="Filtrer les profils">'+''.join(f'<button class="chip {"active" if i==0 else ""}" data-filter="{k}" aria-pressed="{"true" if i==0 else "false"}">{label}</button>' for i,(k,label) in enumerate([('Tous','Tous les profils'),('Leather','Leather'),('Sportswear','Sportswear'),('Rubber','Rubber')]))+'</div>'
save('rencontres','Rencontres',intro('RENCONTRES / LE FEELING D’ABORD','Tes envies.<br><span>Les bons profils.</span>','Un kink en commun. Le reste se découvre à deux.')+f'''<section class="wrap page-content"><div class="search-toolbar"><label class="search-field">{icon('search')}<input id="profile-search" type="search" placeholder="Un pseudo, une ville, un code Kinq…" aria-label="Rechercher un profil"></label><button class="button filter-toggle" aria-expanded="false" aria-controls="extra-filters">{icon('sliders')} Affiner</button></div><div id="extra-filters" class="extra-filters" hidden><label>Ville<select id="city-filter"><option value="">Toutes les villes</option><option>Paris</option><option>Lyon</option><option>Bordeaux</option></select></label><p>La recherche utilise les profils fictifs de cet aperçu. Aucune localisation n’est demandée.</p></div><div class="view-tabs"><button class="active" data-view="all" aria-pressed="true">Découvrir</button><button data-view="pins" aria-pressed="false">{icon('pin')} Mes Pins</button><button data-view="hooks" aria-pressed="false">{icon('hook')} Mes Hooks</button></div>{filters}<p class="demo-note">Photos d’illustration · identités et préférences fictives</p><div class="profiles" id="profiles"></div><div class="empty" hidden><h2>On élargit un peu ?</h2><p>Aucun profil pour cette sélection. Modifie tes critères ou retrouve tous les profils.</p><button class="button" data-reset>Réinitialiser {icon('arrow')}</button></div></section>''')
universes=[('Leather','Le cuir, le gear, les détails qui comptent.','leather'),('Sportswear','Tracksuits, sneakers et énergie street.','sport'),('Rubber','La matière comme seconde peau.','rubber'),('Street & nylon','Des codes urbains, un univers à toi.','street')]
save('kinks','Les kinks',intro('EXPLORER / SUIVRE SA CURIOSITÉ','À chacun<br><span>son univers.</span>','Matières, sensations, dynamiques. Découvre ce qui te parle, sans te coller une étiquette.')+'<section class="wrap page-content"><div class="kink-catalog">'+''.join(f'<a class="kink-tile" href="rencontres.html?kink={"Sportswear" if name=="Street & nylon" else name}"><img src="{photos[photo]}" alt="Illustration de l’univers {name}" loading="lazy"><div><p class="eyebrow">UNIVERS</p><h2>{name}</h2><p>{desc}</p>{icon("up")}</div></a>' for i,(name,desc,photo) in enumerate(universes))+'</div><div class="editorial-banner"><div><p class="eyebrow">PAS BESOIN DE TOUT SAVOIR</p><h2>Un mot t’intrigue ?</h2></div><a class="button" href="lexique.html">Ouvrir le lexique '+icon('arrow')+'</a></div></section>')
save('profil','Un profil à découvrir','<section class="wrap page-content" id="profile-detail"></section>')
# NO TABOO has its own editorial source in build-journal.py.
terms=[('Aftercare','L’attention et les échanges après un moment partagé, selon les besoins et les souhaits de chacun.'),('Consentement','Un accord libre, éclairé, spécifique et réversible. Une préférence sur un profil ne vaut jamais consentement.'),('Dom','Un rôle dominant dans une dynamique négociée. Il ne définit ni toute une personnalité ni une position sexuelle.'),('Gear','Les vêtements et accessoires qui composent un univers fetish : cuir, rubber, sportswear…'),('Hook','Sur Kinq, un signe pour dire « hey, tu me plais », sans envoyer de message.'),('Leather','Un univers autour du cuir, de ses vêtements, accessoires et codes culturels.'),('Limite','Ce que tu ne souhaites pas faire ou partager. Tu n’as pas à justifier un refus.'),('Rubber','Un univers fetish autour du latex et de ses sensations, vêtements et codes esthétiques.'),('Safeword','Un mot ou signal convenu pour demander un arrêt ou une pause. Il ne remplace pas l’attention et le dialogue.'),('Sub','Un rôle soumis dans une dynamique négociée. Ce rôle ne retire jamais le droit de dire non.'),('Switch','Une personne qui peut apprécier différents rôles selon le contexte, le partenaire ou ses envies.')]
save('lexique','Le lexique',intro('LE LEXIQUE / DES MOTS POUR SE COMPRENDRE','Des mots.<br><span>Pas des cases.</span>','Le vocabulaire fetish, simplement. Pour échanger, pas pour t’enfermer.')+'<section class="wrap page-content lexicon"><label class="search-field">'+icon('search')+'<input id="term-search" type="search" aria-label="Rechercher un terme" placeholder="Un mot, une curiosité…"></label><div class="terms">'+''.join(f'<article data-term="{term.lower()}"><h2>{term}</h2><p>{text}</p></article>' for term,text in terms)+'</div><p id="term-empty" hidden>Aucun terme trouvé. Essaie un autre mot.</p></section>')
for slug,title,head,desc,items in [
 ('lieux','Les lieux','Trouve<br><span>ton terrain.</span>','Des adresses pour se rencontrer, découvrir et se sentir à sa place.', [('Bars & rencontres','Faire connaissance','Un premier verre et le temps d’échanger.','sport'),('Clubs & soirées','Partager la nuit','Des espaces pour vivre ton univers ensemble.','rubber'),('Gear & boutiques','Explorer les matières','Découvrir, essayer et trouver ton style.','leather')])]:
 save(slug,title,intro(title.upper()+' / HORS LIGNE',head,desc)+'<section class="wrap page-content"><p class="demo-note">Aperçu de la rubrique · exemples fictifs, aucune adresse ou date réelle</p><div class="destination-grid">'+''.join(f'<article class="destination"><img src="{photos[ph]}" alt="Illustration {name}" loading="lazy"><div><p class="eyebrow">{loc}</p><h2>{name}</h2><p>{txt}</p><button class="underlink" data-modal="coming">Découvrir le concept {icon("up")}</button></div></article>' for name,loc,txt,ph in items)+'</div></section>')
sources=[('Army of Men','Hero puppy — Pup Scout','https://armyofmen.com/products/head-harness-pup-scout-colour'),('MR. Riegillio','Hero sport — duo en PVC','https://mr-riegillio.com/'),('Mike Ruiz / PhotoBook Magazine','Hero leather — Raif & Mark','https://www.photobookmagazine.com/features/leathermen-by-mike-ruiz'),('Ben Orson Leather','Bearback Bulldog Harness','https://www.benorsonleather.com/product-page/bulldog-harness'),('MR. Riegillio','Sylven meets RJ — sportswear / PVC','https://mr-riegillio.com/blogs/about-me/sylven-meets-rj'),('Invincible Rubber','Rubber Vortex Tri Suit','https://www.invinciblerubber.com/rubber-vortex-tri-suit'),('SCALLYCHAV','Shiny Nylon Tracksuit','https://www.scallychav.co.uk/products/pre-sale-shiny-nylon-tracksuit')]
save('credits','Crédits photos',intro('DIRECTION PHOTOGRAPHIQUE / MAQUETTE','Les images<br><span>du concept.</span>','Une sélection photographique de test issue des univers leather, rubber et sportswear fetish.')+'<section class="wrap page-content lexicon"><p>Les photographies illustrent une direction visuelle. Les noms, âges, villes, préférences et relations des profils sont fictifs et ne décrivent pas les personnes photographiées. Aucun partenariat n’est annoncé.</p><p>Les droits de publication commerciale ne sont pas acquis. Cette sélection doit être remplacée ou autorisée avant une mise en ligne publique.</p><div class="terms">'+''.join(f'<article><h2>{name}</h2><p>{desc}<br><a class="underlink" href="{url}" target="_blank" rel="noopener">Consulter la source {icon("up")}</a></p></article>' for name,desc,url in sources)+'</div></section>')
(r/'docs/photo-sources.md').write_text('# Photos de test — 24 septembre 2026\n\nSélection externe pour prototype local, sans droits commerciaux acquis. Aucune affiliation ni préférence réelle attribuée aux personnes photographiées.\n\n'+'\n'.join(f'- [{name}]({url}) — {desc}' for name,desc,url in sources))
